apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform-api
  name: platform-api-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
  selector:
    app: platform-api
