version: '3.5'

services:
    webschool_nginx:
        image: nginx:latest
        container_name: webschool_nginx
        ports:
            - "7000:80"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
            - ./:/var/www
            - ./logs/nginx/:/var/log/nginx:cached
        networks:
          - docker-shared-services
        depends_on:
            - webschool_app

    webschool_app:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: webschool_app
        user: "${UID}"
        volumes:
          - ./:/var/www
          - ./data/composer:/.composer
          - ./logs/symfony:/var/www/var/logs:cached
        environment:
          XDEBUG_CONFIG: "remote_host=192.168.221.1 remote_enable=1"
          PHP_IDE_CONFIG: "serverName=Docker"
        networks:
          - docker-shared-services
        depends_on:
            - mysql

    mysql:
      build:
        context: ./docker/mysql
        dockerfile: ./Dockerfile
      container_name: webschool_db
      environment:
          MYSQL_ROOT_PASSWORD:  wug_school_pass
          MYSQL_DATABASE: wug_school_db
      ports:
          - "3307:3306"
      volumes:
          - ./data/mysql:/var/lib/mysql
      networks:
        - docker-shared-services


networks:
  docker-shared-services:
    external: true
  default:
    external:
      name: nginx-proxy
